### PR TITLE
Update to LLVM 18.1.1 (+ additional commits)

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
Also includes additional commits as the fix for cfi nesting (https://github.com/llvm/llvm-project/pull/83336) is needed for corosensei https://github.com/Amanieu/corosensei/issues/23

So it's just a merge of the upstream release branch.

### CODE REVIEW

**Review by dianqk — APPROVED** [review]
Per https://discourse.llvm.org/t/llvm-18-1-1-released/77540, the 18.1.2 version will be released on the 19th of March. Are you willing to wait for this version?

**Comment by nikic** [comment]
If you do want to pull this ahead of the release, please update to the current release/18.x branch. Some fixes that we need were merged yesterday.

**Comment by ForsakenHarmony** [comment]
@nikic updated

Would be nice to not have to wait another week, but that's up to you.

Renamed the title as it was not correct.

**Comment by nikic** [comment]
Could you please do another merge? Another commit we need landed yesterday. I hope this is the last one...

**Comment by ForsakenHarmony** [comment]
@nikic done

**Pull request merged**
