### PR TITLE
[cherry-pick] Add back aarch64 v8a support

### PR DESCRIPTION
**Pull request by oToToT**
Since 8689f5e6e77394528155b624d74557790278a407, the `generic` CPU for aarch64 is set to the intersection of v8a and v8r.
Therefore, some register like el2_ttbr0 is not supported in default setting.

This patch brings them back on default setting to avoid some backward compatibility problems.

Fixes the Rust part of llvm#53956.

(cherry-picked from 4a31af88a26726f4662a2923618fe45977d09356)

### CODE REVIEW

**Comment by nikic** [comment]
This should probably get an upstream 14.0.x backport?

**Comment by oToToT** [comment]
Yes, this seems reasonable to me to request a backport in LLVM.

Backport request: llvm#55182

**Comment by oToToT** [comment]
It's now backported to LLVM 14.0.5, should I close this PR?

**Comment by nikic** [comment]
Yeah, we should merge this from the upstream branch now. Or probably rebase, as this is the final expected LLVM 14.x release.

**Pull request closed without merging**
