### PR TITLE
Cherry-pick more LLVM 9 fixes

### PR DESCRIPTION
**Pull request by nikic**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
In the interest of avoiding backports too soon, what do you think of rebasing what we have right now? I was able to cleanly rebase with https://github.com/rust-lang/llvm-project/tree/rustc/9.0-2017-07-12 (just rebasing against LLVM's current master commit), and we could presumably do that until this actually lands in rust-lang/rust where we can freeze the base

**Comment by alexcrichton** [comment]
er, I'll rename the branch to 2019, not 2017

**Comment by nikic** [comment]
Sounds good to me. Could you revert https://github.com/rust-lang/llvm-project/commit/af1b3185f55bf52c0c336592c054be8e7afc66ac from the new branch though? It has a known issue that will quite likely cause assertion failures for us.

**Comment by nikic** [comment]
@alexcrichton Or actually just rebase again, a fix was just committed in https://github.com/llvm/llvm-project/commit/9f0d718c662876ee7f97645fdc72ea61ea35549d.

**Comment by alexcrichton** [comment]
Ok I've done a few things:

* You've got write access to this repository (sorry should have done that awhile ago!)
* I've deleted the 2019-07-08 branch
* I've created the 2019-07-12 branch rebased as of a few seconds ago

**Pull request closed without merging**
