### PR TITLE
Handle part-word LL/SC in atomic expansion pass

### PR DESCRIPTION
**Pull request by androm3da**
Differential Revision: https://reviews.llvm.org/D77213

### CODE REVIEW

**Comment by androm3da** [comment]
When I test this locally, `CodeGen/AArch64/wineh-try-catch.ll` fails.  But it also fails on the baseline.

**Comment by androm3da** [comment]
In fact, all these tests fail on baseline:

```
********************
Failing Tests (3):
    LLVM-Unit :: Analysis/./AnalysisTests/TargetLibraryInfoTest.ValidProto
    LLVM :: CodeGen/AArch64/wineh-try-catch.ll
    LLVM :: MC/RISCV/pcrel-fixups.s


```

**Comment by androm3da** [comment]
@cuviper please let me know if this was the right branch to target for current rustc

**Comment by cuviper** [comment]
Looks good, thanks!

**Pull request merged**
