### PR TITLE
[DO NOT MERGE] Apply Rust patches on release/8.x

### PR DESCRIPTION
**Pull request by cuviper**
This PR should not actually be merged, but pushed to a new branch.  I can do this once we're happy with the changes, and decide on a branch name.  FWIW, upstream is naming their stable branches like `release/7.x`, so I suggest a `rust/` prefix here, and indicating it's **pre**-8.0 would be nice too.

- `llvm/`: All patches applied cleanly, or were already upstream, except [8b036feacf91](https://github.com/rust-lang/llvm/commit/8381d3e30329e6bc0c3014b3edd3d5db1e8f3a4b) from rust-lang/llvm#131. That was a revert which I believe has since been fixed properly by [D54997](https://reviews.llvm.org/D54997) -- cc @nikic for verification.

- `clang/`: Rust has no patches AFAICS.

- `lld/`: The one MSVC cmake patch applied fine.

- `lldb/`: All patches applied cleanly except for [8e114ffe6b6a](https://github.com/rust-lang-nursery/lldb/commit/8e114ffe6b6a0f64ac19aa2939ce9d49e036e44c), now 40e425a255be, but I think I resolved that OK.  @tromey, are these patches headed upstream?

I haven't actually tested that this works yet, nor integrated it into the rust repo. :sweat_smile:

### CODE REVIEW

**Comment by nikic** [comment]
> llvm/: All patches applied cleanly, or were already upstream, except 8b036feacf91 from rust-lang/llvm#131. That was a revert which I believe has since been fixed properly by D54997 -- cc @nikic for verification.

That's correct, the revert is no longer necessary.

**Comment by alexcrichton** [comment]
🎊 thanks @cuviper!

For naming, how about:

* `rustc/pre-8.0-2019-01-11` - used when we're between releases
* `rustc/8.0` - used when we've forked off an actual release

(of course open to any other suggestions)

**Comment by nikic** [comment]
@alexcrichton I'd go for always using the `rustc/8.0-2019-01-11` format. Even if we switch to following a release branch rather than master, we'd likely still want to rebase at some point (to switch to the point release if nothing else).

**Comment by cuviper** [comment]
@nikic without any kind of pre-release signifier? I guess I'm OK with that if we're including the snapshot date, as opposed to our current opaque `v1`/`v2` branches.

**Comment by tromey** [comment]
[... lldb patches ...]
> are these patches headed upstream?

No, upstream did not want new language plugins, and instead preferred us to fork.  I'm not completely sure that the troublesome Python config patch is even needed, it might have only been for Linux.

**Comment by cuviper** [comment]
Status: This branch is working well with my rust llvm-monorepo branch ([compare](https://github.com/rust-lang/rust/compare/master...cuviper:llvm-monorepo)). LLVM is scheduled to create the 8.x branch tomorrow, so I plan to rebase once more on that and then submit a rust PR.

**Comment by cuviper** [comment]
This is pushed to `rustc/8.0-2019-01-16`, and the PR is rust-lang/rust#57675.

**Comment by alexcrichton** [comment]
Thanks so much @cuviper!

**Pull request closed without merging**
