### PR TITLE
[WebAssembly] Fix resume-only case in Emscripten EH

### PR DESCRIPTION
**Pull request by tlively**
Summary:
D72308 incorrectly assumed `resume` cannot exist without a `landingpad`,
which is not true. This sets `Changed` to true whenever we make changes
to a function, including creating a call to `__resumeException` within a
function without a landing pad.

Reviewers: tlively

Subscribers: dschuff, sbc100, jgravelle-google, hiraditya, sunfish, llvm-commits

Tags: #llvm

Differential Revision: https://reviews.llvm.org/D73308

### CODE REVIEW

**Comment by tlively** [comment]
This cherry-picks a new fix by @aheejin for https://github.com/rust-lang/rust/issues/66308.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by nikic** [comment]
@tlively Can you please also request a cherry-pick for this change?

**Comment by tlively** [comment]
@nikic If you have permissions to reopen https://github.com/rust-lang/rust/pull/67976, that branch should be good to go with this new update.

**Comment by nikic** [comment]
@tlively Sorry for being unclear, I meant asking Hans for a cherry-pick to the upstream 10.x branch.

Unfortunately it's not possible to reopen that pull request, because GitHub has this weird rule that you can't reopen a pull request if it has been force-pushed in the meantime (one has to first reopen and then force-push).

**Comment by tlively** [comment]
Oh gotcha, yes I will ask Hans to cherry-pick to 10.x. That's too bad about the force push rule. I had been hoping to re-use my old position in the bors queue ;)

**Pull request merged**
