### PR TITLE
[AVR] Cherry pick llvm#85277

### PR DESCRIPTION
**Pull request by Patryk27**
Cherry pick https://github.com/llvm/llvm-project/pull/85277, to fix https://github.com/Rahix/avr-hal/issues/505 🙂

### CODE REVIEW

**Comment by cuviper** [comment]
Can you propose this for upstream backport to `release/18.x`?

**Comment by Patryk27** [comment]
Sure, sure: https://github.com/llvm/llvm-project/pull/85422.

**Comment by Patryk27** [comment]
Oki, got backported!

**Comment by nikic** [comment]
Thanks! We'll pick this patch up when merging the LLVM 18.1.2 release which will be tagged later today. I'll go ahead and close this PR...

**Pull request closed without merging**
