### PR TITLE
Apply patches for RISC-V 64-bit support

### PR DESCRIPTION
**Pull request by Disasm**
This is a minimal subset of patches that can be cherry-picked without any merge conflicts.

After searching for `[RISCV]` in llvm/llvm-project repo I found 21 patches in the interval Jan 17 - Feb 02. Next, I filtered these patches by their ability to be cherry-picked without conflicts. Additionally, one pair of apply+revert patches was filtered out. After the filtering this patch set was reduced to 16 patches.

These 4 patches are absolutely necessary for A, F and D extensions:
* [[RISCV] Add codegen support for RV64A](https://github.com/llvm/llvm-project/commit/07f1c62371c57a66b23933811a585e201dde8e27)
* [[RISCV] Custom-legalise 32-bit variable shifts on RV64](https://github.com/llvm/llvm-project/commit/299d690a502b5a1d56e5e73b2bd7c137b82c20a6) (fix for RV64I)
* [[RISCV] Add RV64F codegen support](https://github.com/llvm/llvm-project/commit/d834d8301d7d2219f4c6c29e7e0906d18a52fbe3)
* [[RISCV] Implement RV64D codegen](https://github.com/llvm/llvm-project/commit/7539fa2c2d1fe54fbb7f9e01ea07ebcec012a144)

With this list in mind, patch set can be reduced to 11 patches (this PR). Another 7 patches are "dependencies": they are needed to cherry-pick without merge conflicts. This patch set cannot be minimized further without merge conflicts.

Closes https://github.com/rust-lang/rust/issues/58335
Related: https://github.com/rust-lang/rust/pull/58012

### CODE REVIEW

**Comment by Disasm** [comment]
cc @asb @alexcrichton @nikic

**Comment by nikic** [comment]
Given the number of patches it might be better to just rebase the fork to current upstream master (and thus ensure that nothing is missing). But I don't see a problem with these cherry-picks either, as this only touches the RISCV backend.

**Comment by Disasm** [comment]
@nikic Rust is able to compile and link an example program with this patch set, so looks like that everything is in place. Rebase will be better, of course, but much harder (at least for me).

**Comment by cuviper** [comment]
I'd rather see us stick to release branches, so that's great if a few backports suffice.

**Comment by alexcrichton** [comment]
Thanks for doing the work here @Disasm! If this works for y'all I agree with @cuviper that it's best to stick to the current commit if we can, so I'm gonna go ahead and merge. It's not impossible to advance to LLVM tip but I think it'll just require a bit more discussion

**Comment by asb** [comment]
It's a bit late but for the desk of completeness: this does indeed seem like a sensible set of RISC-V patches to cherry-pick. Thanks!

**Pull request merged**
