### PR TITLE
Cherry-pick: [X86] Change precision control to FP80 during u64->fp32 conversion on Windows

### PR DESCRIPTION
**Pull request by ghost**
Cherry-pick of llvm/llvm-project@11fb09ec0afa8620bba44f374763e2ad64332e2e that will fix rust-lang/rust#105626.

### CODE REVIEW

**Comment by cuviper** [comment]
I'm wary of jumping the gun on this, especially since a previous attempt was reverted. Lets give it a little time, and maybe you can nominate this for backport to `llvm/release/16.x`?

**Comment by icedrocket** [comment]
> I'm wary of jumping the gun on this, especially since a previous attempt was reverted. Lets give it a little time, and maybe you can nominate this for backport to `llvm/release/16.x`?

This change has already been cherry-picked to release/16.x as aa84ee5cc17e19bfd4f77a55428eca01cf9385d7. The previous attempt forced to use a built-in function, which broke the Chrome build. This approach will just adjust precision control instead of lacking u64 to f32 support.

**Comment by icedrocket** [comment]
> I'm wary of jumping the gun on this, especially since a previous attempt was reverted. Lets give it a little time, and maybe you can nominate this for backport to `llvm/release/16.x`?

This change has already been cherry-picked to release/16.x as aa84ee5cc17e19bfd4f77a55428eca01cf9385d7. The previous attempt used a built-in function, which broke the Chrome build.

**Comment by icedrocket** [comment]
> I'm wary of jumping the gun on this, especially since a previous attempt was reverted. Lets give it a little time, and maybe you can nominate this for backport to `llvm/release/16.x`?

This change has already been cherry-picked to release/16.x as llvm/llvm-project@aa84ee5cc17e19bfd4f77a55428eca01cf9385d7. The previous attempt used a built-in function, which broke the Chrome build.

**Comment by ghost** [comment]
This change has already been cherry-picked to release/16.x as llvm/llvm-project@aa84ee5cc17e19bfd4f77a55428eca01cf9385d7.

**Comment by cuviper** [comment]
I see, thanks -- then that seems ok.

**Pull request merged**
