### PR TITLE
Update LLVM to 19.1.4

### PR DESCRIPTION
**Pull request by Earlopain**
:wave: First-time "contributor". I updated it following https://rustc-dev-guide.rust-lang.org/backend/updating-llvm.html#backports-upstream-supported

LLVM 19.1.4 contains https://github.com/llvm/llvm-project/pull/93890 (backported in https://github.com/llvm/llvm-project/pull/115006) which will fix https://github.com/rust-lang/rust/issues/125619

I reverted 51dee6b64fda7c49a68af78555135c8f51a308cf because it already bumps the version number to 19.1.5. Probably, this is not the best place to choose as the first contribution point. If this doesn't look right, just see this as a notice that some rust issue will be fixed. I'm totally fine with the usual people doing the update like it usually happens

### CODE REVIEW

**Comment by dianqk** [comment]
Thanks! Could you merge `llvmorg-19.1.4` instead of `release/19.x`?

**Comment by Earlopain** [comment]
Yeah, sure. That does make it cleaner for next time around :+1:

**Comment by nikic** [comment]
Hm, the rebase merge option here didn't do what I expected, I thought it was going to rebase only the merge commit...

**Comment by dianqk** [comment]
I have disabled "squash merging" and "rebase merging", but maybe a local fast-forward merge is the best option.

**Pull request merged**
