### PR TITLE
[InstCombine] Fix infinite loop due to bitcast <-> phi transforms

### PR DESCRIPTION
**Pull request by tmandry**
Rust bug: rust-lang/rust#66036

This one should include all the dependent changes this time, and is for the 2019-12-19 branch.
cc @nikic, can you double check that this looks correct?

Fix for https://bugs.llvm.org/show_bug.cgi?id=44245.
Differential Revision: https://reviews.llvm.org/D71164

### CODE REVIEW

**Comment by tmandry** [comment]
Added another cherry-pick so the test can run.

**Comment by nikic** [comment]
This also needs https://reviews.llvm.org/D71209.

**Comment by alexcrichton** [comment]
@tmandry want to push up https://reviews.llvm.org/D71209 and I can merge?

**Comment by tmandry** [comment]
> @tmandry want to push up https://reviews.llvm.org/D71209 and I can merge?

done!

**Pull request merged**
