### PR TITLE
Handle part-word LL/SC in atomic expansion pass

### PR DESCRIPTION
**Pull request by androm3da**
Differential Revision: https://reviews.llvm.org/D77213

### CODE REVIEW

**Comment by androm3da** [comment]
This cherry-pick resolves an assertion I get when trying to build `libstd` for `hexagon-unknown-linux-musl`.

**Comment by cuviper** [comment]
~~Can you try to redo the cherry-pick with the original commit metadata intact? e.g. `git cherry-pick -x ID`.~~

Edit: Oh sorry, you did actually preserve authorship and all. They just didn't keep the commit message the same as the review message, so I thought it was missing. I'll review this in the morning.

**Comment by nikic** [comment]
This commit is against the 10.x branch, while Rust still uses 9.x. The patch looks pretty involved though, so might not be easy to backport.

**Comment by androm3da** [comment]
The commit is technically on upstream master (11.x branch) but applies cleanly to 10.x.  But if it's necessary to put it on 9.x, then I'll look into backporting it.

**Comment by cuviper** [comment]
It's just that rust-lang/rust is still using the 9.x branch, so if you want this to be useful soon, it will have to be applied there. We'll switch to the 10.x branch once we've satisfied the current performance concerns (or we decide to eat that loss).

**Comment by androm3da** [comment]
Sure, makes sense.  Can we consider merging it to 10.x anyways?  Even if it goes into 9.x I'll need it on 10.x branch for when rust upgrades.

It looks like it may not be too hard to backport to 9.x, in progress now.

**Comment by androm3da** [comment]
> Sure, makes sense. Can we consider merging it to 10.x anyways? Even if it goes into 9.x I'll need it on 10.x branch for when rust upgrades.
> 
> It looks like it may not be too hard to backport to 9.x, in progress now.

Created PR #51 -- is that the right 9.x branch?

**Pull request merged**
