### PR TITLE
Pull some upstream patches related to LVI mitigations compile time

### PR DESCRIPTION
**Pull request by jethrogb**
Cherry-pick:
* ec1445c5afda7f145a414f11c9103c87a4c1823f
* 09897b146a8a7cb934279e630c0027d5d4de7399
* 47fe1b63f449827e1171f944b07d0cbebad1de63
* f0f467aeecfc615a5055d8f2edd903996c11727e
* 4b25f672998fde5cc5bb02411e9268b2bb35655f
* 9521704553e8a330cfdf5a0611885680073178b2

This (partially?) addresses https://github.com/rust-lang/rust/issues/74632

### CODE REVIEW

**Comment by jethrogb** [comment]
Ping for review?

**Comment by cuviper** [comment]
@nikic, do you have a sense of how safe these are to backport?

**Comment by nikic** [comment]
@cuviper Not familiar with the code changes here, but in terms of impact this should be fine. LVI changes should only affect people explicitly opting into them (in particular SGX), and I believe that apart from LVI the only other consumer of RDF is the Hexagon target, which is rather obscure (not sure it's even supported by Rust at all). So this shouldn't change anything for standard targets.

**Comment by cuviper** [comment]
OK, works for me.

Note for 3rd-parties: the RDF changes do affect the public API, so you probably don't want this in distro backports, for example.

**Pull request merged**
