### PR TITLE
Backport [TailCallElim] Remove the readonly attribute of byval.

### PR DESCRIPTION
**Pull request by dianqk**
Differential Revision: https://reviews.llvm.org/D156793.

Related issues:
- https://github.com/rust-lang/rust/issues/114312
- https://github.com/llvm/llvm-project/issues/64289

### CODE REVIEW

**Comment by cuviper** [comment]
We just updated to LLVM 17 in rust-lang/rust#114048, local branch `rustc/17.0-2023-07-29`.

Ideally, we would just pick this up after it's backported to the upstream `release/17.x`.

**Comment by dianqk** [comment]
> Ideally, we would just pick this up after it's backported to the upstream `release/17.x`.

I will backport to `release/17.x`. Because this is a miscompilation, I expect to backport to rust beta (1.72.0).

**Comment by cuviper** [comment]
> Because this is a miscompilation, I expect to backport to rust beta (1.72.0).

I nominated the rust issue for T-compiler discussion.

**Comment by dianqk** [comment]
Revert "[clang][WebAssembly] Support wasm32-wasi shared libraries"

We just want to update the beta branch with the necessary fixes.
This branch rustc/16.0-2023-06-05 has completed its mission on the
master branch.
So we can revert this commit for beta updates.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
