### PR TITLE
Cherry pick: Revert "[InlineCost] Check for conflicting target attributes early"

### PR DESCRIPTION
**Pull request by alessandrod**
I would like to propose cherry-picking https://github.com/llvm/llvm-project/commit/b4301df61fc77a9d54ac236bc88742a731285f1c which is the revert/fix for an issue discussed in https://github.com/llvm/llvm-project/issues/65205.

Without this revert we've noticed a lot of inlining failures when compiling for the BPF target. Credit to @qjerome for helping track down the issue.

### CODE REVIEW

**Comment by nikic** [comment]
Please always file for upstream backport first. I have now done so in https://github.com/llvm/llvm-project/issues/65205#issuecomment-1735543581.

**Comment by tamird** [comment]
Now that this landed upstream, can it be cherry-picked?

**Comment by cuviper** [comment]
It was already included when Nikita merged the upstream `release/17.x` branch -- updated in rust-lang/rust#116227 and then backported for 1.73-beta in rust-lang/rust#116279.

**Comment by tamird** [comment]
Ah thanks, it's in https://github.com/rust-lang/llvm-project/tree/rustc/17.0-2023-09-19.

**Pull request closed without merging**
