### PR TITLE
Cherry-pick NoTrapAfterNoreturn fix for wasm backend

### PR DESCRIPTION
**Pull request by majaha**
In trying to enable the option NoTrapAfterNoreturn in rustc, we discovered a bug with that option in the WebAssembly back-end.
The fix was merged into llvm upstream: https://github.com/llvm/llvm-project/pull/65876

And here's the relevant Rust issue, which I'll update when this PR is merged.
https://github.com/rust-lang/rust/pull/110494

### CODE REVIEW

**Comment by cuviper** [comment]
Can you propose this as an upstream llvm-17 backport? That's the preferred route if you can land it that way.

**Comment by nikic** [comment]
I think we should special case this on the rust side instead. That has the benefit that we don't need to make the behavior LLVM-version specific.

**Comment by majaha** [comment]
Which do we think is the best path here? Or maybe it's both?

**Comment by cuviper** [comment]
@nikic It's not clear to me what you're suggesting.

**Comment by nikic** [comment]
@cuviper We can enable NoTrapAfterNoreturn for non-wasm targets only. This backport force-disables the option for wasm, but we can also not enable it in the first place in rustc.

**Comment by cuviper** [comment]
OK, @majaha can you try that in `rustc`? Then we don't need a backport at all, and the special case can be commented to be removed once LLVM 18 is our minimum supported version.

**Comment by majaha** [comment]
Okay, I've pushed a patch over at the other pull request. Let me know what you think.

**Comment by nikic** [comment]
Closing this, as we no longer need this backport with the updated implementation in https://github.com/rust-lang/rust/pull/110494.

**Pull request closed without merging**
