### PR TITLE
[SimplifyCFG][PhaseOrdering] Defer lowering switch into an integer range comparison and branch until after at least the IPSCCP

### PR DESCRIPTION
**Pull request by Amanieu**
That transformation is lossy, as discussed in
https://github.com/llvm/llvm-project/issues/53853
and https://github.com/rust-lang/rust/issues/85133#issuecomment-904185574

This is an alternative to D119839,
which would add a limited IPSCCP into SimplifyCFG.

Unlike lowering switch to lookup, we still want this transformation
to happen relatively early, but after giving a chance for the things
like CVP to do their thing. It seems like deferring it just until
the IPSCCP is enough for the tests at hand, but perhaps we need to
be more aggressive and disable it until CVP.

Fixes https://github.com/llvm/llvm-project/issues/53853
Refs. https://github.com/rust-lang/rust/issues/85133

Reviewed By: nikic

Differential Revision: [reviews.llvm.org/D119854](https://reviews.llvm.org/D119854)

### CODE REVIEW

**Comment by nagisa** [comment]
Is this really something we must backport? I don't recall us doing so all that often, except in the cases where it fixes a serious regression or something of the similar nature.

**Comment by Amanieu** [comment]
I'd rather not wait another 6 months until LLVM 15 to get this optimization, but if you feel strongly about it then I'm happy to close this.

**Comment by nikic** [comment]
There's an upstream backport request for this change. If you can do a perf run to sanity-check this change, I'll approve the upstream backport, so this will be part of LLVM 14 and we don't have to diverge.

**Comment by nikic** [comment]
Perf run started in https://github.com/rust-lang/rust/pull/94424.

I'd also like to have an answer to https://github.com/rust-lang/rust/issues/85133#issuecomment-1053614845, so I can check whether this actually fixes the problem it is supposed to fix.

**Comment by nikic** [comment]
As this doesn't actually address the original issue, I don't think it makes sense to backport this. I have some patched pending that do (together with this) fix it, but I don't think we'll want to backport the whole stack.

**Pull request closed without merging**
